#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASS "YOUR_WIFI_PASSWORD"

#define DHT_PIN  4
#define DHT_TYPE DHT22

#define MQTT_SERVER "MQTT_SERVER_IP_OR_DOMAIN"
#define MQTT_PORT   1883
#define CLIENT_ID   "MY_ESP32"

#define MEASUREMENT_INTERVAL_MS 1800000 // 30 minutes
